---
- name: Check available PHP packages
  hosts: ec2
  become: yes

  tasks:
    - name: Get available PHP packages
      shell: apt-cache search php | grep -E "^php[0-9]"
      register: php_packages
      changed_when: false

    - name: Show PHP packages
      debug:
        var: php_packages.stdout_lines