---
- name: goldenu Git Pull and Restart Apache
  hosts: goldenu
  become: yes

  tasks:
    # - name: Git pull latest code
    #   command: git pull
    #   args:
    #     chdir: /var/www/minthrm/htdocs

    - name: Restart apache2
      shell: /usr/sbin/apachectl graceful